version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: mysql_host
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=mysql_host
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
    - 8080:80

  datascience-notebook:
    container_name: jupyter
    # scipy-notebookの場合はjupyter/scipy-notebookになります。
    image: jupyter/datascience-notebook
    # コンテナの/home/jobyan/workをホストの./workで永続化
    volumes:
      - ./work:/home/jovyan/work
    ports:
      - 8888:8888
    restart: always
    # 今回はローカル起動用なのでログインは省略します。
    command: start.sh jupyter lab --NotebookApp.token=''
  
  streamlit:
    image: zauberzeug/streamlit:latest
    container_name: streamlit
    depends_on: 
      - db
    ports:
      - "8501:8501"
    volumes:
      - "./struns:/usr/src/app/struns"